baseurl = "https://hcy1219.github.io/"
title = "Hsu Chia Yuan"
theme = "hugo-coder"
languagecode = "zh-tw"
defaultcontentlanguage = "zh"

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Hsu Chia Yuan"
    info = "一個在香港求學的臺灣學生"
    description = "Wendy Hsu's personal website"
    keywords = "blog,developer,personal"
    avatarurl = "/images/Me.JPG"

    favicon_32 = "/img/favicon-32x32.png"
    favicon_16 = "/img/favicon-16x16.png"

    #footercontent = ""

    hidecredits = false
    hidecopyright = false

    rtl = false

    math = true
    custom_css = ["css/custom.css"]

# Social links
[[params.social]]
    name = "Github"
    icon = "fab fa-github fa-2x"
    weight = 1
    url = "https://github.com/hcy1219"

[[params.social]]
    name = "Gmail"
    icon = "far fa-envelope fa-2x"
    weight = 2
    url = "1155124446@link.cuhk.edu.hk"

[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin fa-2x"
    weight = 3
    url = "https://www.linkedin.com/in/chia-yuan-hsu-b38036172/"

[[params.social]]
    name = "Instagram"
    icon = "fab fa-instagram fa-2x"
    weight = 4
    url = "https://www.instagram.com/_wendy.hcy/"


# Menu links
    
[[menu.main]]
    name = "About"
    weight = 1
    url = "/About/"

[[menu.main]]
    name = "Resume"
    weight = 2
    url = "/static/CV_HsuChiaYuan_0301.pdf"

[[menu.main]]
    name = "Project"
    weight = 3
    url = "/Project/"









